[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "your authcode "
email = "your qq email"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

 [rabbitmqConfig]
  host= "rabbitmq"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"

 [ragModelConfig]
  embeddingModel= "text-embedding-v4"
  chatModelName="qwen-turbo"
  docDir = "./docs"
  baseUrl="https://dashscope.aliyuncs.com/compatible-mode/v1"
  dimension=1024

  [voiceServiceConfig]
  voiceServiceApiKey = "baiduApiKey"
  voiceServiceSecretKey ="baiduSecretKey"

  [agentConfig]
  enableAgent = true
  skillDir = "../dclaw/skills"
  memoryDir = "./data/memory"
  maxToolCalls = 1
  enableSkill = true
  enableMemory = true
  enableMCP = true
